### ISSUE TITLE
Redirect Oauth Option (1)

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/temp_app#10]
We want the ability to oauth one of our customer's accounts without them landing in ledger sync's app. Instead, they'd just get redirected through. So the route would go like:

`Modern Treasury App --> L.S. Redirect --> QBO (Auth) --> L.S. Redirect --> MT App`

**Comment by ryanwjackson** [comment]
I'm thinking we will need something like this (assuming https://ls.moderntreasury.com is the app host):

`https://ls.moderntreasury.com/auth/:token?redirect=https://ls.moderntreasury.com/ledgers/quickbooks_online/new?redirect=https://moderntreasury.com`

We will have to encode the second redirect or something, but this requires us to do the following:

1. Add `redirect` to the auth controller when authenticating users.
2. Add `redirect` to the `quickbooks_online` oauth flow and redirect on success.  To make this generic, we will probably have to add a separate thru controller after connection that will handle the redirect.  Then every ledger connection controller can redirect thru there on success.

@mattgmarcus Does that make sense?

**Comment by mattgmarcus** [comment]
Yeah I think this make sense. Just one point to clarify on:

When they get redirected to `https://ls.moderntreasury.com/ledgers/quickbooks_online/new`, would the user automatically get redirected to QBO? That is the flow we'd want - we don't want them to see ledgersync and have to click in there to sync again

**Comment by ryanwjackson** [comment]
Yes, that's just a redirect action on that controller.

As for not seeing the app, we could make a config setting to also always redirect to the config login_url (e.g. mt.com/login) when no session exists, regardless of where they are.  This is a separate ticket, and they would still have access if they are authenticated.  But it would cut down on some interaction.

**Comment by mattgmarcus** [comment]
Yeah that could be a separate ticket. I can add that
