### ISSUE TITLE
Rename Account to Organization (1)

### ISSUE THREAD

**Issue by ryanwjackson** [LedgerSync/temp_app#11]
**Is your feature request related to a problem? Please describe.**
The worked "account" is very common and prescriptive in the accounting world.  It creates confusion, as the notion of an `Account` in the app is representative of a business user and the collection of its users.

**Describe the solution you'd like**
Rename the `Account` model to `Organization` and all associated references.

**Describe alternatives you've considered**
- We discussed other names for `Account` here in the app
- We discussed other names for `Account` here in the library

**Comment by ryanwjackson** [comment]
Also, IMO as the app is not being used yet, we can go ahead and do this without zero-downtime migrations.

**Comment by mattgmarcus** [comment]
Yeah I agree, no need to optimize for zero-downtime yet
