### ISSUE TITLE
Webhooks (2-5)

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/temp_app#13]
This is just for enabling webhooks on the sync's endpoint

**Comment by ryanwjackson** [comment]
I'd say we add ability to cancel rather than delete, just for logging purposes.  Does that make sense?  If so, I can make a separate issue for creating that functionality.

**Comment by mattgmarcus** [comment]
Yeah canceling a sync works. When you make the ticket, can you put at the bottom of the board? Thanks

**Comment by ryanwjackson** [comment]
@mattgmarcus tracked in #16 

Mind sharing the code for the idempotency and signed signatures?
