### ISSUE TITLE
CRUD API Endpoints for ledger resources (2)

### ISSUE THREAD

**Issue by mattgmarcus** [LedgerSync/temp_app#9]
We want the ability to create/update/read/delete a ledger resource in Ledger Sync without performing an actual sync. This can be useful when we know an entity already exists in the ledger so we don't want to overwrite its attributes/perform an operation

**Comment by mattgmarcus** [comment]
Yeah I think you need the ability to delete at least. I'd be fine with removing the update operation from the list. In that case, you would have to do 2 operations: delete and then a new create. That does tend to be safer. What do you think?

**Comment by ryanwjackson** [comment]
It's somewhat trivial to add the update operation if we do the others, so I
say do all 4.


--
Ryan Jackson
ryanwjackson@gmail.com

**Comment by mattgmarcus** [comment]
Cool, it's more about not giving people the ability to shoot themselves in the foot by accident. But I could also see people wanting the endpoint, so like you said, it's trivial to add while we're there

**Comment by ryanwjackson** [comment]
Ok, so we will add the following: 

*CRUD `/resources`*
- `account_id`(LSA `id` for the account)
- `type`
- `external_id` (provider's `id` for the resource)


*CRUD `/ledger_resources`*
- `resource_ledger_id`(the ledger's `id` for the resource, aka external)
- `resource_id` (LSA `id` for the `resource`)
- `ledger_id` (LSA `id` for the `ledger`)

Make sense?

**Comment by mattgmarcus** [comment]
Yup

**Comment by ryanwjackson** [comment]
@mattgmarcus (or anyone), do you have any code for API pagination for the index routes?  I'm going to skip for now.

**Comment by mattgmarcus** [comment]
@ryanwjackson 
You can use https://github.com/davidcelis/api-pagination and https://github.com/kaminari/kaminari

with this in `config/initializers/api_pagination.rb`
```
# frozen_string_literal: true

Kaminari.configure do |config|
  config.default_per_page = 25
  config.max_per_page     = 100
end

ApiPagination.configure do |config|
  config.paginator = :kaminari

  config.page_header = "X-Page"
  config.total_header = "X-Total-Count"
  config.per_page_header = "X-Per-Page"

  config.page_param = :page
  config.per_page_param = :per_page
end
```
